name: Continuous Deployment
 
on: 
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
       
        script: |
          cd ~/mulia/mulia_web
          git pull origin master
          yarn build
          serve -s build